name: Scanner
on:
  push:
  pull_request:
jobs:
  scanner:
    name: Scan Repo
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: trivy_repo_scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "template"
          template: "@/github/workspace/jetstream-turbo/.github/trivy-html.tpl"
          output: trivyscan.md
          severity: "CRITICAL,HIGH,MEDIUM"
          github-pat: ${{ github.token }}

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: trivyscan.md
